"""empty message

Revision ID: 466c71e71ea2
Revises: a4c625022d31
Create Date: 2020-03-04 13:29:28.285250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466c71e71ea2'
down_revision = 'a4c625022d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
