"""empty message

Revision ID: 752cf80ab7a8
Revises: a6762633e9f6
Create Date: 2020-04-26 17:47:16.160311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752cf80ab7a8'
down_revision = 'a6762633e9f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commentid', sa.Integer(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commentid'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    # ### end Alembic commands ###
