"""empty message

Revision ID: 8510f01e41d4
Revises: cafbe5639bba
Create Date: 2020-04-26 12:53:11.357950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8510f01e41d4'
down_revision = 'cafbe5639bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('projectid', sa.Integer(), nullable=True),
    sa.Column('username', sa.CHAR(length=50), nullable=True),
    sa.Column('commenttime', sa.DATE(), nullable=True),
    sa.Column('repliedname', sa.CHAR(length=50), nullable=True),
    sa.Column('content', sa.VARCHAR(length=300), nullable=True),
    sa.Column('star', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['projectid'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
