"""empty message

Revision ID: 8de6cfba4f0b
Revises: 1772774c9fd8
Create Date: 2020-03-24 21:16:28.207971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8de6cfba4f0b'
down_revision = '1772774c9fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('status', sa.VARCHAR(length=100), nullable=True))
    op.add_column('project', sa.Column('uploadtime', sa.DATE(), nullable=True))
    op.add_column('project', sa.Column('userid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'userid')
    op.drop_column('project', 'uploadtime')
    op.drop_column('project', 'status')
    # ### end Alembic commands ###
