"""empty message

Revision ID: cafbe5639bba
Revises: 
Create Date: 2020-04-26 12:51:56.318921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cafbe5639bba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'userid')
    op.drop_column('comment', 'replyid')
    op.create_unique_constraint(None, 'user', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.add_column('comment', sa.Column('replyid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('comment', sa.Column('userid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
