"""empty message

Revision ID: cf712e3c4366
Revises: 634a03c88b31
Create Date: 2020-04-26 18:50:02.103104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf712e3c4366'
down_revision = '634a03c88b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('like_ibfk_3', 'like', type_='foreignkey')
    op.drop_constraint('like_ibfk_2', 'like', type_='foreignkey')
    op.drop_constraint('like_ibfk_1', 'like', type_='foreignkey')
    op.drop_column('like', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.create_foreign_key('like_ibfk_1', 'like', 'comment', ['commentid'], ['id'])
    op.create_foreign_key('like_ibfk_2', 'like', 'user', ['userid'], ['id'])
    op.create_foreign_key('like_ibfk_3', 'like', 'project', ['projectid'], ['id'])
    # ### end Alembic commands ###
